<?php

/**
 * @author Mygento Team
 * @copyright 2026 Mygento (https://www.mygento.com)
 * @package Mygento_Slider
 */

namespace Mygento\Slider\Model\EntityResolver;

use Magento\Catalog\Api\Data\CategoryInterface;
use Magento\Catalog\Model\ResourceModel\Category\Collection;
use Magento\Catalog\Model\ResourceModel\Category\CollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\GraphQl\Query\Uid;
use Mygento\Slider\Api\EntityResolverInterface;

class Category implements EntityResolverInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private Uid $uidEncoder,
        private ResourceConnection $resourceConnection,
        private CollectionFactory $factory,
    ) {}

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    public function resolveName(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $collection = $this->getCollection($ids);
        $result = [];
        /** @var CategoryInterface $category */
        foreach ($collection as $category) {
            $result[(string) $category->getId()] = sprintf(
                '[Category ID: %s] %s',
                $category->getId(),
                $category->getName(),
            );
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, array{url: string|null, entity_identifier: string}>
     */
    public function resolveData(array $ids, int $storeId): array
    {
        $result = [];
        $urls = $this->resolveUrl($ids, $storeId);
        $collection = $this->getCollection($ids);
        $collection->addFieldToFilter(
            CategoryInterface::KEY_IS_ACTIVE,
            1,
        );
        /** @var CategoryInterface $category */
        foreach ($collection as $category) {
            $id = (string) $category->getId();
            $result[$id] = [
                'url' => $urls[$id] ?? null,
                'entity_identifier' => $this->uidEncoder->encode($category->getId()),
            ];
        }

        return $result;
    }

    /**
     * @param string[] $ids
     */
    private function getCollection(array $ids): Collection
    {
        /** @var Collection $collection */
        $collection = $this->factory->create();
        $collection->setStoreId(0);
        $collection->addAttributeToSelect(CategoryInterface::KEY_NAME);
        $collection->addFieldToFilter('entity_id', ['in' => $ids]);

        return $collection;
    }

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    private function resolveUrl(array $ids, int $storeId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', 'category')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }
}
