<?php

/**
 * @author Mygento Team
 * @copyright 2026 Mygento (https://www.mygento.com)
 * @package Mygento_Slider
 */

namespace Mygento\Slider\Model\EntityResolver;

use Magento\Cms\Api\Data\PageInterface;
use Magento\Cms\Model\ResourceModel\Page\Collection;
use Magento\Cms\Model\ResourceModel\Page\CollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Mygento\Slider\Api\EntityResolverInterface;

class Page implements EntityResolverInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private ResourceConnection $resourceConnection,
        private CollectionFactory $factory,
    ) {}

    public function resolveName(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $result = [];
        $collection = $this->getCollection($ids);
        foreach ($collection as $page) {
            $result[(string) $page->getId()] = sprintf(
                '[Page ID: %s] %s',
                $page->getId(),
                $page->getTitle(),
            );
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, array{url: string|null, entity_identifier: string}>
     */
    public function resolveData(array $ids, int $storeId): array
    {
        $result = [];
        $urls = $this->resolveUrl($ids, $storeId);
        $collection = $this->getCollection($ids);
        $collection->addFieldToFilter(
            PageInterface::IS_ACTIVE,
            1,
        );
        /** @var PageInterface $page */
        foreach ($collection as $page) {
            $id = (string) $page->getId();
            $result[$id] = [
                'url' => $urls[$id] ?? null,
                'entity_identifier' => $page->getIdentifier(),
            ];
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    private function resolveUrl(array $ids, int $storeId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', 'cms-page')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }

    /**
     * @param string[] $ids
     */
    private function getCollection(array $ids): Collection
    {
        /** @var Collection $collection */
        $collection = $this->factory->create();
        $collection->addFieldToFilter(
            PageInterface::PAGE_ID,
            ['in' => $ids],
        );
        $collection->addFieldToSelect([
            PageInterface::IDENTIFIER,
            PageInterface::PAGE_ID,
            PageInterface::TITLE,
        ]);

        return $collection;
    }
}
