<?php

/**
 * @author Mygento Team
 * @copyright 2026 Mygento (https://www.mygento.com)
 * @package Mygento_Slider
 */

namespace Mygento\Slider\Model\EntityResolver;

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\ResourceModel\Product\Collection;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Mygento\Slider\Api\EntityResolverInterface;

class Product implements EntityResolverInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private ResourceConnection $resourceConnection,
        private CollectionFactory $factory,
    ) {}

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    public function resolveName(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $collection = $this->getCollection($ids);
        $result = [];

        /** @var ProductInterface $product */
        foreach ($collection as $product) {
            $id = (string) $product->getId();
            $result[$id] = sprintf(
                '[Product SKU: %s] %s',
                $product->getSku(),
                $product->getName(),
            );
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, array{url: string|null, entity_identifier: string}>
     */
    public function resolveData(array $ids, int $storeId): array
    {
        $result = [];
        $collection = $this->getCollection($ids);
        $urls = $this->resolveUrl($ids, $storeId);
        $collection->addAttributeToFilter('status', Status::STATUS_ENABLED);
        /** @var ProductInterface $product */
        foreach ($collection as $product) {
            $id = (string) $product->getId();
            $result[$id] = [
                'url' => $urls[$id] ?? null,
                'entity_identifier' => $product->getSku(),
            ];
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    private function resolveUrl(array $ids, int $storeId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', 'product')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }

    /**
     * @param string[] $ids
     */
    private function getCollection(array $ids): Collection
    {
        /** @var Collection $collection */
        $collection = $this->factory->create();
        $collection->setStoreId(0);
        $collection->addAttributeToSelect([ProductInterface::SKU, ProductInterface::NAME]);
        $collection->addFieldToFilter('entity_id', ['in' => $ids]);

        return $collection;
    }
}
