type Slider {
    title: String!
    identity: String!
    options: SliderOptions!
    banners: [Banner!]! @doc(description: "List of banners in the slider")
}
type Banner {
    image: String!
    link: String!
    name: String!
    image_formats: Formats! @doc(description: "List image formats")
}

type Formats {
    avif: FormatImages
    webp: FormatImages
    jpg: FormatImages
}

type FormatImages {
    image: [ImageSizeLink!]
    small_image: [ImageSizeLink!]
}

type ImageSizeLink {
    size: String!
    link: String!
}
type BreakpointsImages {
    url: String!
    format: String!
}

type SliderOptions {
    dots: Boolean!
    width: String!
    height: String!
    arrows: Boolean!
    preload: Boolean!
    autoplay: Boolean!
    infinite: Boolean!
    lazyLoad: Boolean!
    per_page: String!
    breakpoint: String!
    width_small: String!
    height_small: String!
    autoplay_interval: String!
}

type ProductSlider {
    title: String!
    identity: String!
    options: ProductSliderOptions!
    parameters: Parameters!
    items: [SliderProduct!]!
}

type SliderProduct @doc(description: "Contains product details") {
    product: ProductInterface! @doc(description: "Product.") @resolver(class: "Magento\\CatalogGraphQl\\Model\\Resolver\\Product")
    image_formats: [Formats]! @doc(description: "List image formats")
}

type ProductSliderOptions {
    dots: Boolean!
    webp: Boolean!
    width: String!
    height: String!
    arrows: Boolean!
    preload: Boolean!
    autoplay: Boolean!
    infinite: Boolean!
    lazyLoad: Boolean!
    per_page: String!
    breakpoint: String!
    width_small: String!
    height_small: String!
    autoplay_interval: String!
}

type Parameters {
    products_count: String!
    sort_order: String!
}

type Query {
    slider(
        identity: String!,
    ): Slider @resolver(class: "Mygento\\Slider\\Model\\Resolver\\Slider")

    productSlider(
        identity: String!,
    ): ProductSlider @resolver(class: "Mygento\\Slider\\Model\\Resolver\\ProductSlider")
}