type Slider {
    title: String!
    identity: String!
    options: SliderOptions!
    banners: [Banner!]! @doc(description: "List of banners in the slider")
}

type SliderOptions {
    dots: Boolean!
    arrows: Boolean!
    preload: Boolean!
    autoplay: Boolean!
    infinite: Boolean!
    lazyLoad: Boolean!
    width: String
    height: String
    per_page: String
    breakpoint: String
    width_small: String
    height_small: String
    autoplay_interval: String
}

type Banner {
    image: String!
    link: String!
    name: String!
    image_formats: SliderImageFormats! @doc(description: "List image formats")
}

type SliderImageFormats {
    avif: ImageFormatData
    webp: ImageFormatData
    jpg: ImageFormatData
    default: ImageFormatData
}

type ImageFormatData {
    image: ImageSizeLink
    small_image: ImageSizeLink
}

type ImageSizeLink {
    size: String
    link: String
}

type Query {
    slider(
        identity: String!,
    ): Slider @resolver(class: "Mygento\\Slider\\Model\\Resolver\\Slider")
}