<?php

/**
 * @author Mygento Team
 * @copyright 2026 Mygento (https://www.mygento.com)
 * @package Mygento_Slider
 */

declare(strict_types=1);

namespace Mygento\Slider\Model\Builder;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\UrlInterface;

class LinkBuilder implements DataBuilderInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private ResourceConnection $resourceConnection,
        private UrlInterface $urlBuilder,
        private string $urlRewriteEntityType,
        private string $targetPathPattern,
    ) {}

    public function addData(array $items, array $entityIds, int $storeId): array
    {
        $requestPaths = $this->getRequestPaths($entityIds, $storeId);
        foreach ($items as &$item) {
            $entityId = (int) ($item['entity_identifier'] ?? 0);
            $path = $requestPaths[$entityId] ?? sprintf($this->targetPathPattern, $entityId);
            $item['link'] = $this->urlBuilder->getDirectUrl($path, ['_scope' => $storeId]);
        }
        unset($item);

        return $items;
    }

    private function getRequestPaths(array $entityIds, int $storeId): array
    {
        $ids = array_map('intval', $entityIds);
        if (!$ids) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', $this->urlRewriteEntityType)
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }
}
